name: network
description: A starting point for Dart libraries or applications.
version: 1.1.2
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.1
  logger: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2
